# copied from pascal and more

# arguments for dataset
dataset: tless
nclass: 31
crop_size: 512 # maybe try lower
data_root: /data/tless
split: 1_2
valset: test_primesense

# arguments for training
epochs: 30
batch_size: 8 # per GPU x 1 GPUs
lr: 0.02
lr_multi: 1.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95

# arguments for model
model: deeplabv3plus
backbone: resnet101
replace_stride_with_dilation: [False, False, True]
dilations: [6, 12, 18]
